version: '2'
services:
  # proxy:
  #   build:
  #     context: ${MICRB106_PATH}/services/proxy
  #   labels:
  #     - "traefik.enable=true" # Enable reverse-proxy for this service
  #     - "traefik.frontend.rule=Host:micrb106.${HOST}"

  haxcms:
    build:
      context: ${MICRB106_PATH}/services/haxcms
    volumes:
      - /var/www/html/dist
      - /var/www/html/build
      - ${MICRB106_PATH}:/var/www/html/
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:micrb106.${HOST}"

  r-service:
    build:
      context: ${MICRB106_PATH}/services/r-service
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:micrb106.${HOST}; Path:/service/r-service"

  glossary-service:
    build:
      context: ${MICRB106_PATH}/services/glossary-service
    labels:
      - "traefik.enable=true" # Enable reverse-proxy for this service
      - "traefik.frontend.rule=Host:glossary-service.micrb106.${HOST}"