version: '2'
services:
  proxy:
    build:
      context: ./services/proxy
    ports:
      - '80:80'
  haxcms:
    build:
      context: ./services/haxcms
    volumes:
      - /usr/share/nginx/html/dist
      - /usr/share/nginx/html/build
      - .:/usr/share/nginx/html/
  r-service:
    build:
      context: ./services/r-service